### ISSUE TITLE
Обработка кликов пользователя по маркеру на карте.

### ISSUE THREAD

**Issue by DemyanchikVadim** [pub-t/bus-schedule#8]

**Comment by irnc** [comment]
Что нужно сделать? _Разместить_ маркеры на карте? Или _показать иконки встобусов_ в маркерах? @DemyanchikVadim уточни пожалуйста в заголовке.

**Comment by DemyanchikVadim** [comment]
Done - [https://github.com/pub-t/bus-schedule/blob/master/client/app.js](this)
